/* user/wasm_test.c - Test WASM3 syscalls from user space */

// Syscall wrappers (inline assembly for int 0x80)
#define SYS_LOG 3
#define SYS_EXIT 1
#define SYS_WASM_LOAD 13
#define SYS_WASM_EXEC 14

static inline long syscall1(long num, long arg1) {
    long ret;
    __asm__ volatile (
        "movq %1, %%rdi\n"
        "int $0x80\n"
        "movq %%rax, %0\n"
        : "=r"(ret)
        : "r"(num), "r"(arg1)
        : "rdi", "rax", "memory"
    );
    return ret;
}

static inline long syscall3(long num, long arg1, long arg2, long arg3) {
    long ret;
    __asm__ volatile (
        "movq %1, %%rdi\n"
        "movq %2, %%rsi\n"
        "movq %3, %%rdx\n"
        "int $0x80\n"
        "movq %%rax, %0\n"
        : "=r"(ret)
        : "r"(num), "r"(arg1), "r"(arg2), "r"(arg3)
        : "rdi", "rsi", "rdx", "rax", "memory"
    );
    return ret;
}

void sys_log(const char *msg) {
    syscall1(SYS_LOG, (long)msg);
}

void sys_exit(int code) {
    syscall1(SYS_EXIT, code);
}

int sys_wasm_load(const void *wasm_bytes, unsigned long len, const char *name) {
    return (int)syscall3(SYS_WASM_LOAD, (long)wasm_bytes, len, (long)name);
}

int sys_wasm_exec(int module_id, const char *func_name) {
    return (int)syscall3(SYS_WASM_EXEC, module_id, (long)func_name, 0);
}

// Embedded WASM test module (compiled from test.wat)
// This is a placeholder - will be generated by wat2wasm
const unsigned char test_wasm[] = {
    0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,  // WASM magic + version
    0x01, 0x0c, 0x03,                                // Type section
    0x60, 0x02, 0x7f, 0x7f, 0x01, 0x7f,             // (i32, i32) -> i32 for add
    0x60, 0x01, 0x7f, 0x01, 0x7f,                   // (i32) -> i32 for factorial
    0x60, 0x00, 0x01, 0x7f,                         // () -> i32 for get_magic_number
    
    0x03, 0x04, 0x03, 0x00, 0x01, 0x02,             // Function section: 3 functions
    
    0x07, 0x2a, 0x03,                                // Export section: 3 exports
    0x03, 0x61, 0x64, 0x64, 0x00, 0x00,             // "add" -> func 0
    0x09, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x00, 0x01,  // "factorial" -> func 1
    0x10, 0x67, 0x65, 0x74, 0x5f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x00, 0x02,  // "get_magic_number" -> func 2
    
    0x0a, 0x26, 0x03,                                // Code section: 3 function bodies
    
    // Function 0: add (a, b) { return a + b; }
    0x07, 0x00, 0x20, 0x00, 0x20, 0x01, 0x6a, 0x0b,
    
    // Function 1: factorial (simplified stub for now)
    0x07, 0x00, 0x20, 0x00, 0x41, 0x01, 0x6a, 0x0b,
    
    // Function 2: get_magic_number { return 42; }
    0x04, 0x00, 0x41, 0x2a, 0x0b
};

const unsigned int test_wasm_len = sizeof(test_wasm);

void _start(void) {
    sys_log("WASM Test: Starting...");
    
    // Load WASM module
    sys_log("WASM Test: Loading module...");
    int module_id = sys_wasm_load(test_wasm, test_wasm_len, "test_module");
    
    if (module_id < 0) {
        sys_log("WASM Test: FAILED to load module");
        sys_exit(1);
    }
    
    sys_log("WASM Test: Module loaded successfully!");
    
    // Execute get_magic_number function
    sys_log("WASM Test: Executing get_magic_number()...");
    int result = sys_wasm_exec(module_id, "get_magic_number");
    
    if (result == 42) {
        sys_log("WASM Test: SUCCESS! get_magic_number() returned 42");
    } else {
        sys_log("WASM Test: ERROR - unexpected result");
    }
    
    sys_log("WASM Test: Complete!");
    sys_exit(0);
}
